/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankovaaplikacia;

/**
 *
 * @author matejmajerik
 */
public class Bankomat extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Bankomat.class.getName());
    
    //definovanie premmenych pre triedu Bankomat
    public Ucet Matej;
    public Ucet Jozef;
    public Ucet Lucia;
    
    public Ucet aktualnyUcet;
    /**
     * Creates new form Bankomat
     */
    public Bankomat() {
        initComponents();
        
        //priradenie konkretnych dat po starte aplikacie
        this.Matej = new Ucet(1234, "Matej Majerik", 250, 1500, "SK22 1100 0000 7890", 159753);
        this.Jozef = new Ucet(123456, "Jozef Mrkvicka", 50000, 150000, "SK22 0000 7891", 753159);
        this.Lucia = new Ucet(4321, "Lucia Valova", 2400, 5000, "SK22 0000 7891", 124578);
    
        polickoMeno.setVisible(false);
        polickoPin.setVisible(false);
        tlacidloPotvrdit.setVisible(false);
        
        labelZostatok.setVisible(false);
        tlacidloVybrat.setVisible(false);
        tlacidloVlozit.setVisible(false);
        
        labelMenoText.setVisible(false);
        jLabel4.setVisible(false);
 
   }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tlacidloVyberKodom = new javax.swing.JButton();
        tlacidloVlozitKartu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelMenoText = new javax.swing.JLabel();
        polickoMeno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        polickoPin = new javax.swing.JPasswordField();
        tlacidloPotvrdit = new javax.swing.JButton();
        labelZostatok = new javax.swing.JLabel();
        tlacidloVybrat = new javax.swing.JButton();
        tlacidloVlozit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tlacidloVyberKodom.setText("2. Výber pomocou kódu");
        tlacidloVyberKodom.addActionListener(this::tlacidloVyberKodomActionPerformed);

        tlacidloVlozitKartu.setText("1.  Vložiť kartu");
        tlacidloVlozitKartu.addActionListener(this::tlacidloVlozitKartuActionPerformed);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Dobrý deň, vyberte si akciu\"");

        labelMenoText.setText("Meno");

        polickoMeno.setText("jTextField1");

        jLabel4.setText("PIN");

        polickoPin.setText("jPasswordField1");

        tlacidloPotvrdit.setText("Potvrdit prihlásenie");
        tlacidloPotvrdit.addActionListener(this::tlacidloPotvrditActionPerformed);

        labelZostatok.setText("Aktuálny zostatok");

        tlacidloVybrat.setText("Vybrať 50 €");
        tlacidloVybrat.addActionListener(this::tlacidloVybratActionPerformed);

        tlacidloVlozit.setText("Vložiť 50 €");
        tlacidloVlozit.addActionListener(this::tlacidloVlozitActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tlacidloVlozitKartu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tlacidloVyberKodom)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tlacidloVlozit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tlacidloVybrat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(tlacidloPotvrdit)
                        .addGap(88, 88, 88)
                        .addComponent(labelZostatok)
                        .addGap(27, 27, 27))))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMenoText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(polickoPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(polickoMeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMenoText)
                    .addComponent(polickoMeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6))
                    .addComponent(polickoPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(labelZostatok)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tlacidloVybrat))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(tlacidloPotvrdit)))
                        .addGap(18, 18, 18)
                        .addComponent(tlacidloVlozit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tlacidloVyberKodom)
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tlacidloVlozitKartu)
                                .addGap(37, 37, 37))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tlacidloVlozitKartuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlacidloVlozitKartuActionPerformed
            // TODO add your handling code here:
            Prihlasovanie sluzba = new Prihlasovanie();
            
           Ucet prihlasenyUcet = sluzba.overUzivatela(Matej, Jozef, Lucia);
           
           if(prihlasenyUcet !=null){
               KonzoloveMenu menu = new KonzoloveMenu();
               menu.menuPoPrihlaseni(prihlasenyUcet);
           }
    }//GEN-LAST:event_tlacidloVlozitKartuActionPerformed

    private void tlacidloVyberKodomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlacidloVyberKodomActionPerformed
        // TODO add your handling code here:
         VyberHotovostiPomocouKodu sluzba = new VyberHotovostiPomocouKodu();
         sluzba.overUzivatela(Matej,Jozef,Lucia);
    }//GEN-LAST:event_tlacidloVyberKodomActionPerformed

    private void tlacidloPotvrditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlacidloPotvrditActionPerformed

        String meno = polickoMeno.getText();
        int pin = Integer.parseInt(polickoPin.getText());

        // Tvoj pôvodný if-else, ktorý dokonale poznáš
        if (meno.equals(Matej.meno) && pin == Matej.pin) {
            this.aktualnyUcet = Matej;
        } else if (meno.equals(Jozef.meno) && pin == Jozef.pin) {
            this.aktualnyUcet = Jozef;
        } else if (meno.equals(Lucia.meno) && pin == Lucia.pin) {
            this.aktualnyUcet = Lucia;
        }

        if (this.aktualnyUcet != null) {
            // Skryjeme prihlasovacie políčka
            polickoMeno.setVisible(false);
            polickoPin.setVisible(false);
            tlacidloPotvrdit.setVisible(false);

            // Ukážeme tlačidlá na vklad a výber
            tlacidloVybrat.setVisible(true);
            tlacidloVlozit.setVisible(true);

            // Zavoláme tvoju triedu Zostatok a ukážeme ju v okienku
            Zostatok z = new Zostatok();
            javax.swing.JOptionPane.showMessageDialog(this, z.aktualnyZostatok(aktualnyUcet));
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Zlé meno alebo PIN!");
        }
    }//GEN-LAST:event_tlacidloPotvrditActionPerformed

    private void tlacidloVlozitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlacidloVlozitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlacidloVlozitActionPerformed

    private void tlacidloVybratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlacidloVybratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlacidloVybratActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Bankomat().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelMenoText;
    private javax.swing.JLabel labelZostatok;
    private javax.swing.JTextField polickoMeno;
    private javax.swing.JPasswordField polickoPin;
    private javax.swing.JButton tlacidloPotvrdit;
    private javax.swing.JButton tlacidloVlozit;
    private javax.swing.JButton tlacidloVlozitKartu;
    private javax.swing.JButton tlacidloVyberKodom;
    private javax.swing.JButton tlacidloVybrat;
    // End of variables declaration//GEN-END:variables
}
