/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankovaaplikacia;


/**
 *
 * @author matejmajerik
 */




public class GUI extends javax.swing.JFrame {
    private Ucet matej = new Ucet(1234,"Matej Majerik", 250,1500,"SK22 1100 0000 7890",159753);
    private Ucet jozef = new Ucet(123456,"Jozef Mrkvicka",50000,150000,"SK22 0000 7891",753159);
    private Ucet lucia = new Ucet(4321,"Lucia Valova",2400,5000,"SK22 0000 7891",124578);

    private Ucet prihlaseny = null;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        
        vystupLabel.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(394, 239));
        
     //vypnut vsetky akcie    
    jButton2.setEnabled(false);
    jButton3.setEnabled(false);
    jButton4.setEnabled(false);
    jButton5.setEnabled(false);

       
    // default text
    vystupLabel.setText("Vitajte, prosím prihláste sa.");
 
    //reset panel
    jPanel1.removeAll();
    jPanel1.revalidate();
    jPanel1.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vystupLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        menoField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pinField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vystupLabel.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N

        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        jButton4.setText("Stav účtu");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton3.setText("Vklad");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton2.setText("Výber");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton5.setText("Odhlásiť");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        menoField.addActionListener(this::menoFieldActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Meno");

        pinField.addActionListener(this::pinFieldActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("PIN");

        loginBtn.setText("Prihlásiť");
        loginBtn.addActionListener(this::loginBtnActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(menoField, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(pinField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(loginBtn)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(vystupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vystupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menoFieldActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        
        
// zrusenie aktualne prihlaseneho
prihlaseny = null;

// vystup sprava
vystupLabel.setText("Odhlásený");

// zablokovanie tlacidiel vyber vklad stav uctu, odhlasit
jButton2.setEnabled(false); // Výber
jButton3.setEnabled(false); // Vklad
jButton4.setEnabled(false); // Stav účtu
jButton5.setEnabled(false); // Odhlásiť

//vycistenie panelu
jPanel1.removeAll();
jPanel1.revalidate();
jPanel1.repaint();

// vycisetenie meno, PIN
menoField.setText("");
pinField.setText("");

        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
       

String meno = menoField.getText();
int pin;

try {
    pin = Integer.parseInt(new String(pinField.getPassword())); // ✅ TOTO
} catch (Exception e) {
    vystupLabel.setText("PIN musí byť číslo");
    return;

}

Prihlasovanie p = new Prihlasovanie();

Ucet ucet = p.overUzivatela(meno, pin, matej, jozef, lucia);

if (ucet != null) {
    prihlaseny = ucet;
    vystupLabel.setText("Vitajte " + ucet.getMeno());
    
    //vycistenie panelu
    jPanel1.removeAll();
    jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT)); //presmerovanie na lavu stranu
  
    jPanel1.revalidate();
    jPanel1.repaint();

    
    
    //vycistenie policiek
    menoField.setText("");
    pinField.setText("");

    
    // zaponutie tlacitok
    jButton2.setEnabled(true);
    jButton3.setEnabled(true);
    jButton4.setEnabled(true);
    jButton5.setEnabled(true);


    
} else {
    vystupLabel.setText("Zlé meno alebo PIN");
    }  


    }//GEN-LAST:event_loginBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        

if (prihlaseny == null) {
    vystupLabel.setText("Najprv sa prihlás");
    return;
}
   
        
jPanel1.removeAll();


//layout
 jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));


// pole na zadanie sumy
javax.swing.JTextField sumaField = new javax.swing.JTextField(10);

// button potvrdiť
javax.swing.JButton potvrditBtn = new javax.swing.JButton("Potvrdiť");

// label na výsledok
javax.swing.JLabel vysledok = new javax.swing.JLabel("");

// pridanie do panelu
jPanel1.add(new javax.swing.JLabel("Zadaj sumu:"));
jPanel1.add(sumaField);
jPanel1.add(potvrditBtn);
jPanel1.add(vysledok);

// akcia po kliknutí
potvrditBtn.addActionListener(e -> {

    int suma;

    try {
        suma = Integer.parseInt(sumaField.getText());
    } catch (Exception ex) {
        vysledok.setText("Zlá suma");
        return;
    }

    VyberHotovosti v = new VyberHotovosti();

    String result = v.vyber(prihlaseny, suma);

    vysledok.setText(result);
});

// refresh panelu
jPanel1.revalidate();
jPanel1.repaint();

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
// kontrola prihlásenia
if (prihlaseny == null) {
    vystupLabel.setText("Najprv sa prihlás");
    return;
}

// vyčistenie panelu
jPanel1.removeAll();
jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

// input na sumu
javax.swing.JTextField sumaField = new javax.swing.JTextField(10);

// button
javax.swing.JButton potvrditBtn = new javax.swing.JButton("Potvrdiť");

// label výsledok
javax.swing.JLabel vysledok = new javax.swing.JLabel("");

// pridanie komponentov
jPanel1.add(new javax.swing.JLabel("Zadaj sumu na vklad:"));
jPanel1.add(sumaField);
jPanel1.add(potvrditBtn);
jPanel1.add(vysledok);

// akcia po kliknutí
potvrditBtn.addActionListener(e -> {

    int suma;

    try {
        suma = Integer.parseInt(sumaField.getText());
    } catch (Exception ex) {
        vysledok.setText("Zlá suma");
        return;
    }

    VkladHotovosti v = new VkladHotovosti();

    String result = v.vklad(prihlaseny, suma);

    vysledok.setText(result);
    
    //navrat na hlavnu obrazovku
    
    
    
    //po jednej sekunde reset
    javax.swing.Timer t = new javax.swing.Timer(2000, ev -> {
    jPanel1.removeAll();
    jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
    
    //navrat do menu
    jPanel1.add(new javax.swing.JLabel("Vyberte operáciu"));
    
    jPanel1.revalidate();
    jPanel1.repaint();
  
});
t.setRepeats(false);
t.start();

    
});

// refresh
jPanel1.revalidate();
jPanel1.repaint();

        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pinFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinFieldActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
 
        // kontrola prihlásenia
if (prihlaseny == null) {
    
        //sprava do labelu
        vystupLabel.setText("Najprv sa prihlás");
        return;
    }
    //vycisti panel( text, ktory tam bol)
    jPanel1.removeAll();
    
 
    //logika za zostatkou
    Zostatok z = new Zostatok();
    String stav = z.aktualnyZostatok(prihlaseny);

    ZostatokSporiaciUcet zs = new ZostatokSporiaciUcet();
    String spor = zs.aktualnyZostatokSporiaci(prihlaseny);

    
    //titulok + 2 hondnoty
    jPanel1.setLayout(new java.awt.GridLayout(3,1));
    jPanel1.add(new javax.swing.JLabel("--------------------STAV ÚČTU--------------------"));
    jPanel1.add(new javax.swing.JLabel(stav)); //osobny ucet
    jPanel1.add(new javax.swing.JLabel(spor)); //sporiaci ucet


    // akcia na obnovenie GUI kvoli zemen obsahu
    jPanel1.revalidate();
    jPanel1.repaint();
    
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    
public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> new GUI().setVisible(true));
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField menoField;
    private javax.swing.JPasswordField pinField;
    private javax.swing.JLabel vystupLabel;
    // End of variables declaration//GEN-END:variables
}
